feat: train identifier persistence (#217)
SchweizerischeBundesbahnen/DAS pull request #391
Opened 2024-11-18 16:36 UTC by mghilardelli

closes #217

2024-11-19 07:55 UTC, rawi-coding requested changes

2024-11-19 07:55 UTC, rawi-coding commented on backend/src/main/kotlin/ch/sbb/backend/application/rest/TrainNumberDto.kt
> +        example = "1727188352.001"
Double finde ich nicht besonders sinnvoll für Timestamp. Lieber mit ISO oder INT arbeiten.

2024-11-19 09:09 UTC, mghilardelli commented on backend/src/main/kotlin/ch/sbb/backend/application/rest/TrainNumberController.kt
> +
betriebstag

2024-11-19 09:10 UTC, mghilardelli commented on backend/src/main/kotlin/ch/sbb/backend/application/rest/TrainNumberController.kt
> +    fun addTrainNumbers(@RequestBody trainNumbers: List<TrainNumberDto>) {
insert, update, delete aufgrund keys nummer, ru, betriebstag

2024-11-19 09:11 UTC, mghilardelli commented on backend/src/main/kotlin/ch/sbb/backend/application/rest/TrainNumberDto.kt
> +    val number: String,
identifier

2024-12-05 13:59 UTC, rawi-coding approved these changes

2024-12-05 13:59 UTC, rawi-coding commented on preload/src/main/kotlin/ch/sbb/das/preload/PreloadApplication.kt
> +	runApplication<PreloadApplication>(*args)
Spacing ist irgendwie nicht konsistent.

2024-12-05 15:03 UTC, merged