feat: added next stop (#200)
SchweizerischeBundesbahnen/DAS pull request #438
Opened 2024-12-03 14:32 UTC by tobe-official

2024-12-03 16:09 UTC, Grodien commented on das_client/applicationSupportPath/logs/das-log-lastSavedFile.json
das file sollte nicht eingechecked werden

2024-12-03 16:10 UTC, Grodien commented on das_client/integration_test/test/train_journey_table_test.dart
> +        await tester.dragUntilVisible(
bitte noch line length auf 120 stellen, da es sonst viel umformiert

2024-12-03 20:47 UTC, Grodien requested changes

2024-12-03 20:47 UTC, Grodien commented on das_client/integration_test/test/train_journey_test.dart
> +      await prepareAndStartApp(tester);
Am besten hier direkt auch noch die Eingabe einbauen. Der Test wird failen sobald wir die default werte entfernen

2024-12-03 20:47 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/main_container.dart
> +    return StreamBuilder<Journey?>(
ich würde den StreamBuilder an den Anfang vom MainContainer setze. Die weiteren Felder werden diesen auch noch brauchen

2024-12-03 20:47 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/main_container.dart
> +          return Text(journey.metadata.nextStop!.name.localized,
journey.metadata.nextStop?.name.localized ?? context.l10n.c_unknown

so sparst du dire das ganze If und den Text unten

2024-12-06 10:01 UTC, tobe-official commented on das_client/applicationSupportPath/logs/das-log-lastSavedFile.json
Wie sollte ich es dann auslassen? Soll ich das File ins .gitignore hinzufügen oder einfach hier rauslöschen? (Über die drei Punkte beim File)

2024-12-09 13:39 UTC, Grodien requested changes

2024-12-09 13:39 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/main_container.dart
> +          final Journey? journey = snapshot.data;
hier direkt auf null prüfen, ohne journey macht es wenig sinn den screen to rendern, dann muss es später im _nextStopText nicht mehr machen.

2024-12-10 13:35 UTC, Grodien approved these changes

2024-12-10 13:51 UTC, merged