feat: added visualization of non standard track equipment (#82)
SchweizerischeBundesbahnen/DAS pull request #470
Opened 2024-12-17 10:04 UTC by rawi-coding

2024-12-18 08:41 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/table/cells/track_equipment_render_data.dart
render DATA class unter widget? 🤔

2024-12-18 09:38 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/table/cells/track_equipment_render_data.dart
> +  factory TrackEquipmentRenderData.from(Journey journey, int index) {
Man könnte das wohl einiges effizienter machen, wenn man einfach die cumulativeHeight von der vorheriger Row nehmen würde, statt jede row berechnet es für sich neu... aber denke sollte nicht zu einem problem führen

2024-12-18 09:41 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/table/cells/track_equipment_render_data.dart
Diese Klasse kann man noch gut unit-testen. please add some

2024-12-18 09:42 UTC, Grodien requested changes
Sieht gut aus, noch paar unit tests dann ist perfekt

2024-12-19 09:00 UTC, rawi-coding commented on das_client/lib/app/pages/journey/train_journey/widgets/table/cells/track_equipment_render_data.dart
Ja war mir auch unsicher wegen der Location... da es aber sehr stark ans `track_equipment_cell_body.dart` gebunden ist, würde ich es mal hier lassen.

Ja stimmt, werde noch paar Unit-Tests ergänzen 👍

2024-12-19 09:03 UTC, rawi-coding commented on das_client/lib/app/pages/journey/train_journey/widgets/table/cells/track_equipment_render_data.dart
> +  factory TrackEquipmentRenderData.from(Journey journey, int index) {
Ja das stimmt. Ich fand's so etwas besser lesbar und die Performanz sollte kein Problem sein. Die Heights der Rows sind statisch und er geht immer nur soweit zurück, wie der TrackEquipmentType gleich ist. Das werden vermutlich nie viele Elemente sein.

Wenns für dich passt, lasse ich das vorerst so.

2024-12-19 11:38 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/train_journey.dart
you broke something :/

2024-12-19 11:43 UTC, Grodien approved these changes
lgtm

2024-12-19 11:46 UTC, merged