122 puenktlichkeit anzeige
SchweizerischeBundesbahnen/DAS pull request #473
Opened 2024-12-20 11:43 UTC by tobe-official

2024-12-20 12:53 UTC, rawi-coding requested changes

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +                    '05:43:00',
Das ist nicht in deiner Story drin, aber du könntest hier noch die aktuelle Systemzeit anzeigen.

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +    return StreamBuilder<Journey?>(
Der StreamBuilder sollte weiter unten im Widget-Tree verwendet werden. Die Journey brauchst du nur im `_punctualityDisplay`, deshalb sollte der StreamBuilder auch auf dieser Stufe sein.

Das sollte zwar nicht vorkommen, aber prüfe trotzdem wie das UI aussieht, wenn die Journey nicht oder noch geladen wird. Da du den StreamBuilder verschiebst, musst du das evtl. anders lösen.

![image](https://github.com/user-attachments/assets/be4139f8-f59d-476e-a118-c1d9fb3932a0)

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/sfera/src/mapper/sfera_model_mapper.dart
> +  static Duration _stringToDuration(String stringToChange) {
Ich würde diese Logik gleich im "Domain-Model" Delay führen, z.B. eine `toDuration()` Methode.

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/sfera/src/mapper/sfera_model_mapper.dart
> +      throw FormatException('Invalid ISO 8601 duration format');
Ich würde hier eine Warnung loggen und null zurückgeben. Besser wir zeigen die Pünktlichkeit nicht an, statt ein Fehler zu werfen.

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/sfera/src/mapper/sfera_model_mapper.dart
> +            ? '+PT0M0S' //Base Value for when the information is Null
In diesem Fall wäre es sinnvoller, einfach `null` den Metadaten zu übergeben.

2024-12-20 12:53 UTC, rawi-coding commented on das_client/lib/sfera/src/model/train_location_information.dart
> +
nitpick: new Line zu viel.

2024-12-20 12:53 UTC, rawi-coding commented on das_client/pubspec.yaml
> +  iso_duration: ^0.1.1
nitpick: Damits einheitlich bleibt, noch die URL darüber kopieren wie bei den anderen.

2025-01-06 09:53 UTC, Grodien commented on das_client/ios/Podfile.lock
> +COCOAPODS: 1.15.2
cocoapods bei dir noch updaten, dieser change reverten

2025-01-06 09:54 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +            snapshot.data!.metadata.delay == null) {
wenn delay null ist würde ich eher einfach nichts anzeigen statt ein ProgressIndicator

2025-01-06 10:02 UTC, Grodien commented on das_client/pubspec.yaml
> +  iso_duration: ^0.1.1
Sind wir uns sicher dass wir dieses Package verwenden wollen?
- Last Version 16 Month ago
- Unverified Publisher
- 1 Like only

2025-01-06 10:09 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +        final String formattedDuration = '${delay.isNegative ? '-' : '+'}$hours:$minutes:${seconds.padLeft(2, '0')}';
wenn stunden gesetzt sind sollte minuten wohl auch immer zweistellig dargestellt werden?

2025-01-06 10:10 UTC, Grodien requested changes
paar kleine anmerkungen

2025-01-06 10:22 UTC, rawi-coding commented on das_client/pubspec.yaml
> +  iso_duration: ^0.1.1
@Grodien Ich habe das vor den Ferien mit Raphael besprochen. Wir nehmen die Library aber decken unsere Cases mit Unit-Tests ab. Nicht ganz glücklich die Library, sie hat aber zumindest keine Abhänigkeiten. Solang es funktioniert, würde ich sie verwenden.

2025-01-10 08:25 UTC, tobe-official commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +        final String formattedDuration = '${delay.isNegative ? '-' : '+'}$hours:$minutes:${seconds.padLeft(2, '0')}';
Ich habe nachgefragt, es ist gewollt, dass das Format mm:ss bleibt und nicht hh:mm:ss wird. Ich fixe aber noch dass es immer zweistellig ist. 👍

2025-01-14 11:43 UTC, Grodien requested changes

2025-01-14 11:43 UTC, Grodien commented on das_client/lib/sfera/src/model/delay.dart
> +      return null;
warning loggen

2025-01-14 11:43 UTC, Grodien commented on das_client/lib/sfera/src/model/delay.dart
> +  static Duration? toDuration(String? stringToChange) {
statt static methode wär es schöner einen getter wie "Duration? get delayAsDuration => " zu haben.

2025-01-14 11:43 UTC, Grodien commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +      final String minutes = NumberFormat('00').format(delay.inMinutes.abs() % 60);
was passiert bei delay > 60 min? Was sagt UX dazu?

2025-01-14 12:50 UTC, tobe-official commented on das_client/lib/app/pages/journey/train_journey/widgets/header/time_container.dart
> +      final String minutes = NumberFormat('00').format(delay.inMinutes.abs() % 60);
Es wird aktuell noch abgeklärt. Es wird aber so sein, dass daraus eine eigene Story gemacht wird.

2025-01-17 10:52 UTC, Grodien approved these changes
lgtm

2025-01-17 11:09 UTC, rawi-coding approved these changes

2025-01-17 11:10 UTC, merged